steps:
  # Dockerイメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/git-push-pray-frontend:$COMMIT_SHA"
      - "./frontend" # フロントエンドディレクトリを指定

  # Artifact Registryにプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/git-push-pray-frontend:$COMMIT_SHA"

  # Cloud Runにデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "git-push-pray-frontend"
      - "--image"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/git-push-pray-frontend:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"

images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/git-push-pray-frontend:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
