# エラーがある場合にビルド・デプロイをしてしまうとページが正常に見れなくなるので、エラーがあるかどうかを事前にチェックするためのワークフロー
name: Lint And Build Check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "frontend/src/**"

jobs:
  lint-and-build-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.x"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Build
        run: npm run build
